@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor Administrator
participant ":System" as System

activate Administrator
    Administrator -> System : initiates the process of registering a new vaccine
    activate System
        System --> Administrator : prompts for required attributes (Name, Brand, Vaccine Type)
    deactivate System

    Administrator -> System : enters necessary information
    activate System
        System --> Administrator : validates entered data and requests confirmation
    deactivate System

    Administrator -> System : confirms registration
    activate System
        System --> Administrator : records the information and notifies the success of the operation
    deactivate System
deactivate Administrator

@enduml
